config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username,
            presence: true,
            uniqueness:{case_sensitive:false},
            length:{minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:105},
            uniqueness: {case_sensitive: false},
            format:{ with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger]="You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only:[:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page:5)
  end

  def new
    @article = Article.new
  end

  def create

    @article = Article.new(article_params)
    @article.user = current_user
    #render plain: article_params.inspect
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
      end
  end

  def edit

    #render plain: article_params.inspect
  end

  def update

    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy

    @article.destroy

    redirect_to articles_path
    flash[:danger] = "Article was successfully deleted"
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title,:description, category_ids:[])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except:[:index, :show]

  def index
    @categories = Category.paginate(page:params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end

  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:dange] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id]= nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page:5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles by user have been deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:dabger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options ={ size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class="article-body">
        <%= truncate(article.description, length: 100) %>
        <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user%>,
                          <%= time_ago_in_words(article.created_at) %> ago,
                          last updated: <%= time_ago_in_words(article.updated_at) %>
          </small>
        </div>
      </div>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %><p>
      <% end %>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions">
          <%= link_to "Edit article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete article", article_path(article), method: :delete, data: {confirm: "Delete Article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>'

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class:"form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class:"form-control", placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %><br/>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows:10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
          <%= link_to "Cancel", articles_path, class: "btn btn-danger btn-lg" %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="center description"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user %>
  <ul class="listing">
    <div class="row center">
      <div class="well col-md-4 col-md-offset-4">
        <li> Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete article", article_path(@article), method: :delete, data: {confirm: "Delete Article?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
    <%= link_to "View all articles", articles_path,  class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
  <div class="control-label col-sm-2">
    <%= f.label :name %>
  </div>
  <div class="col-sm-8">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-lg' %>
<% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center"> Listing All Categories</h1>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li> <small><%= pluralize(category.articles.count, "article") %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Create new category </h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Categor: " + @category.name %></h1>
<div align="center">
  <% if logged_in? and current_user.admin? %>
  <div class="row">
    <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
  </div>
  <% end %>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category.articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright&copy;2019 by Marcio
      </small>
      <nav>
        <ul>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </footer>
  </div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class:"navbar-brand",id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to "All Category", categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <% if logged_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create New Category", new_category_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <%= "[Admin]" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Profile",user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<br>
<h1 style="font-family:Helvetica;">About Alpha Blog</h1>
<p style="font-family:Helvetica;"> Alpha Blog was inspired by our undying drive of self-improvement, growth and thirst for knowledge. The site was made possible by the vision of many other Alphas before us who invented and kept on improving the vision of what Ruby could be and Ruby is!
</p>


-----------------------------------------
START CONTAINERS
-----------------------------------------<br /><br /><br />
<div class="player container">
  <div class="player row">
    <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-2">

      <div class="player col-xs-12">
        IMAGE --------------<br />
        --------------------<br />
        --------------------<br />
        --------------------<br />
        --------------------<br />
      </div>
      <div class="player col-xs-12">
        Marcio Correa <br />
        Sex: Male<br />
        Height: 5'11"<br />
        Weight: 160 lbs<br />
        Location: [US] Boston, MA
      </div>
    </div>

    <div class="player col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-10">

<!-- THIS IS WHERE THE SPORTS TABLE STARTS -->
      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Volleyball | Setter / Any <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>
          <div class="player row">
            <div class="player col-xs-3">
              CBVA<br />
              B
            </div>
            <div class="player col-xs-3">
              USAV<br />
              B
            </div>
            <div class="player col-xs-3">
              NAGVA<br />
              B
            </div>
            <div class="player col-xs-3">
              Yankee<br />
              B
            </div>
          </div>
      </div>

      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Volleyball | Setter / Any <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>
          <div class="player row">
            <div class="player col-xs-3">
              CBVA<br />
              B
            </div>
            <div class="player col-xs-3">
              USAV<br />
              B
            </div>
            <div class="player col-xs-3">
              NAGVA<br />
              B
            </div>
            <div class="player col-xs-3">
              Yankee<br />
              B
            </div>
          </div>
      </div>

      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Volleyball | Setter / Any <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>
          <div class="player row">
            <div class="player col-xs-3">
              CBVA<br />
              B
            </div>
            <div class="player col-xs-3">
              USAV<br />
              B
            </div>
            <div class="player col-xs-3">
              NAGVA<br />
              B
            </div>
            <div class="player col-xs-3">
              Yankee<br />
              B
            </div>
          </div>
      </div>

      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Volleyball | Setter / Any <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>
          <div class="player row">
            <div class="player col-xs-3">
              CBVA<br />
              B
            </div>
            <div class="player col-xs-3">
              USAV<br />
              B
            </div>
            <div class="player col-xs-3">
              NAGVA<br />
              B
            </div>
            <div class="player col-xs-3">
              Yankee<br />
              B
            </div>
          </div>
      </div>

      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Ultimate Frisbee | Setter / Any <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>

      </div>

      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Soccer | Setter / Any <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>
          <div class="player row">
            <div class="player col-xs-3">
              CBVA<br />
              B
            </div>
            <div class="player col-xs-3">
              USAV<br />
              B
            </div>
            <div class="player col-xs-3">
              NAGVA<br />
              B
            </div>
            <div class="player col-xs-3">
              Yankee<br />
              B
            </div>
          </div>
      </div>

      <div class="player col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
        Tennis <br />
        Intermediate<br />
        <br />
        Ratings
        <hr>
          <div class="player row">
            <div class="player col-xs-3">
              CBVA<br />
              B
            </div>
          </div>
      </div>
<!-- this is where the sports table ends -->
    </div>
  </div>
</div>

app/views/pages/footer.html.erb
<p style="font-family: Helvetica; width:100%;position: fixed; bottom: 0; text-align-last:center;">
<br>
<strong>Alpha Blog</strong> (C)2019 - JK
<br>
</p>

app/views/pages/header.html.erb
<p style="font-family: Helvetica;text-align: center;background-color:#ffffe6"><%= image_tag 'alpha-blog_logo.png' %>
<br>
<%= link_to 'Home', root_path %> | <%= link_to 'Blog', articles_path %> | <%= link_to 'About Us', about_path %>
</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1> Alpha Blog </h1>
    <p><%= link_to "Sign Up Now!!!", signup_path, class:"btn btn-danger btn-lg btn-xlarge" %></p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved.
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li> <%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
      <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        <% end %>
        <%= link_to "Cancel request and return to articles listing", articles_path,  class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div align="center">
  <% obj.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          <% if logged_in? and current_user.admin? %>
          <li> <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Delete user and all their articles?" } %> </li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Blogges </h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'user', obj: @users %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s Profile </h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s Articles</h4>

<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>